name: "LogChimp"

services:
  db:
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - logchimp

  api:
    image: ghcr.io/logchimp/logchimp/api:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${API_PORT:-8000}
      LOGCHIMP_SECRET_KEY: ${LOGCHIMP_SECRET_KEY}

      # Database
      LOGCHIMP_DB_HOST: db
      LOGCHIMP_DB_DATABASE: ${POSTGRES_DB}
      LOGCHIMP_DB_PORT: 5432
      LOGCHIMP_DB_USER: ${POSTGRES_USER}
      LOGCHIMP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      LOGCHIMP_DB_SSL: ${LOGCHIMP_DB_SSL:-false}

      # Mail
      LOGCHIMP_MAIL_HOST: ${LOGCHIMP_MAIL_HOST}
      LOGCHIMP_MAIL_USER: ${LOGCHIMP_MAIL_USER}
      LOGCHIMP_MAIL_PASSWORD: ${LOGCHIMP_MAIL_PASSWORD}
      LOGCHIMP_MAIL_PORT: ${LOGCHIMP_MAIL_PORT}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    networks:
      - logchimp

  theme:
    image: ghcr.io/logchimp/logchimp/theme:latest
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${THEME_PORT:-3000}
      VITE_API_URL: http://api:${API_PORT:-8000}
    ports:
      - "${THEME_PORT:-3000}:${THEME_PORT:-3000}"
    networks:
      - logchimp

networks:
  logchimp:
    driver: bridge

volumes:
  postgres:
